// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_god = "CgkI19K_ku8cEAIQBQ"; // <GPGSID>
        public const string achievement_divinely = "CgkI19K_ku8cEAIQBA"; // <GPGSID>
        public const string achievement_yhooo = "CgkI19K_ku8cEAIQAw"; // <GPGSID>
        public const string achievement_not_bad = "CgkI19K_ku8cEAIQAQ"; // <GPGSID>
        public const string achievement_jolly_fine = "CgkI19K_ku8cEAIQAg"; // <GPGSID>
        public const string achievement_do_not_despair = "CgkI19K_ku8cEAIQCQ"; // <GPGSID>
        public const string leaderboard_king_of_points = "CgkI19K_ku8cEAIQBg"; // <GPGSID>
        public const string achievement_phoenix = "CgkI19K_ku8cEAIQCg"; // <GPGSID>
        public const string leaderboard_king_of_coins = "CgkI19K_ku8cEAIQCw"; // <GPGSID>

}

